#!/bin/sh /etc/rc.common

START=99
STOP=1
USE_PROCD=1

start_service() {
	config_load fancontrol
	local enable
	config_get_bool enable settings enable 1
	[ "$enable" -eq 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/bin/fancontrol
	procd_set_param respawn 5 10 0
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger fancontrol
}
